export const GAME_CONFIG = {
  PA_PER_TURN: 3,
  MAX_TURNS_PER_YEAR: 4,
  TURNS_TO_WIN: 20,
  
  VICTORY_CONSENSUS_THRESHOLD: 80,
  VICTORY_TECH_LEVEL: 3,
  VICTORY_SPACE_UNLOCK: 'lunar_colony',
  
  AI_THINK_TIME_MS: 500,
  AI_MAX_ACTIONS: 3,
  AI_AGGRESSION_SCALE: 0.3,
  
  BASE_GDP: 1000,
  BASE_GROWTH: 2.5,
  BASE_INFLATION: 2.0,
  BASE_DEBT: 0,
  BASE_RESERVES: 100,
  
  BASE_CONSENSUS: 50,
  CONSENSUS_DRIFT_RANGE: 3,
  
  BASE_TECH_LEVEL: 1,
  TECH_PROGRESS_PER_TURN: 10,
  
  TOTAL_NATIONS: 58,
  PLAYABLE_NATIONS: 1,
  AI_NATIONS: 57,
  
  MAP_CENTER: [0, 0] as [number, number],
  MAP_ZOOM: 1.5,
  
  TURN_TIMEOUT_MS: 30000,
  AI_ROUND_TIMEOUT_MS: 60000,
  
  EVENT_RETENTION_DAYS: 30,
  MAX_EVENTS_SHOWN: 100,
  
  MAX_FACTIONS_SHOWN: 6,
  SIDEBAR_WIDTH: 320,
  
  DEBUG_MODE: import.meta.env.DEV,
  LOG_AI_DECISIONS: import.meta.env.DEV,

  SPY: {
    MAX_AGENTS: 10,
    AGENT_STARTING_LEVEL: 1,
    AGENT_XP_PER_MISSION: 10,
    BASE_SUCCESS_RATE: 0.5,
    COVER_BLOW_THRESHOLD: 0.8,
  },

  COLD_WAR: {
    TENSION_THRESHOLD: 80,
    CRISIS_TURNS: 3,
    ESCALATION_RATE: 5,
    DEESCALATION_RATE: 10,
    PROVOCATION_COST: 15,
  },

  SECURITY: {
    BASE_LEVEL: 30,
    COUNTER_SPY_EFFECTIVENESS: 0.3,
    SURVEILLANCE_RANGE: 50,
    ENCRYPTION_BONUS: 0.2,
  },

  SPACE: {
    BASE_COST_MULTIPLIER: 1.0,
    HEAVY_BONUS: { cargo: 0.5, defense: 0.3 },
    LIGHT_BONUS: { speed: 0.4, cost: 0.2 },
    FAST_BONUS: { deployment: 0.5, attack: 0.4 },
    ECONOMY_BONUS: { tourism: 0.4, profit: 0.3 },
  },
} as const;

export type GameConfig = typeof GAME_CONFIG;
export default GAME_CONFIG;